name: "PR CI"

# Trigger when a pull request is created or code is updated as well as when the PR is merged to main
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: "Build and Test"
    if: ${{ github.event_name == 'push' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v3

      - name: "Check for .nvmrc"
        run: |
          if [[ ! -f .nvmrc ]]; then
            echo "14" > .nvmrc
          fi

      - name: "Setup - Use Node.js (from .nvmrc)"
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@digital-uk'
          always-auth: true

      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: "Install dependencies"
        id: install_deps
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_GITHUB_ACTIONS_TOKEN }}

      # `npm rebuild` will run all those post-install scripts for us.
      - name: "Setup dependencies"
        id: setup_deps
        run: npm rebuild && npm run prepare --if-present

      - name: "Compile"
        id: build
        run: npm run build

      - name: "Lint"
        id: lint
        run: |
          npm run tslint --if-present | tee -a tslint-output.md
          echo "### Lint Output" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat tslint-output.md >> $GITHUB_STEP_SUMMARY
